openapi: 3.0.1
info:
  title: JS Code Interpreter with code sandbox
  description: A plugin that allows the user to create a JS project in code sandbox using ChatGPT.
  version: 'v1'
servers:
  - url: http://localhost:3000
    descripton: localhost server
  - url: https://sandbox-api.com/v1
    descripton: Sandbox server
paths:
  /api/code-interpreter:    
    post:
      operationId: create codeSandBox
      summary: Create codeSandbox 
      parameters:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createCodeSandboxRequest'
      responses:
        "200":
          description: OK
    

components:
  schemas:    
    createCodeSandboxRequest:
      type: object
      required:
      - todo
      properties:
        todo:
          type: string
          description: The todo to add to the list.
          required: true    