openapi: 3.0.1
info:
  title: JS Code Interpreter with code sandbox
  description: A plugin that allows the user to create a JS project in code sandbox using ChatGPT.
  version: 'v1'
servers:  
  - url: https://js-code-interpreter.vercel.app/
    descripton: Sandbox server
paths:
  /api/code-interpreter:    
    post:
      operationId: codeSandBox
      summary: Create codeSandbox       
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createCodeSandboxRequest'
      responses:
        "200":
          description: OK

components:
  schemas:    
    createCodeSandboxRequest:
      type: object      
      properties:
        files:
          type: object
          description: The JS code to create a code Sandbox
          required: true    
      required:
        - files
